version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: rms_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# =============
# 1. DBeaver
# =============
# 2. Data Population Script
# =============

# - User type: [type: [employee, admin], username, password, municipality, status, email]
#
# - Resource: [
# Name: ,
# Category: ["Μηχανήματα","Οχήματα","Εξοπλισμός","Εργαλεία","Υλικά Κατασκευών","Άλλο",],
# Quantity,
# Unit: ["Τεμάχια", "Κιλά", "Μέτρα", "Λίτρα", "Τόνοι"],
# Description:
# Status: ["Σε χρηση", "Διαθεσιμο"]
# Distance
# ]
#
# - Requests
#
# - Reports
#
# - Transaction
#
# - Audits
